#day5 homework

name = input ( " whats your name: " )
surname = input ( " whats your surname: " )
age = input ( " how old are you: " )
country = input ( " in which country do you live: " )
city = input ( " where do you live: " )
street_adress = input ( " which is your street: " )
food = input ( "which is your favourite food: " )
drink = input ( " which is your favourite drink: " )
sport = input ( " which is your favourite sport: " )
facebook = input ( " what is your facebook username: " )
instagram = input ( " what is your instagram username: " )
twitter = input ( " what is your twitter username: " )
telegram = input ( " what is your telegram username: " )
bereal = input ( " what is your bereal username: " )
snapchat = input ( " what is your snapchat username: " )
discord = input ( " what is your discord username: " )
duolingo = input ( " what is your duolingo username: " )
sololearn = input ( " what is your sololearn username: " )
facetime = input ( " what is your facetime username: " )
zoom = input ( " what is your username: " )
google_clasroom = input ( " what is your google_clasroom username: " )
canva = input ( " what is your canva username: " )
gmail = input ( "whats your gmail username " )
wifi = input ( " what is your wifi passsword: " )

print ( "chemi saxelia" + " " + name + " " + "chemi gvaria" + " " + surname + " " + "chemi asakia" + " " + age + " " + "chemi qvekhana aris" + " " + country + " " + "me vcxovrob" + " " + city + " " + "chemi quchaa" + " " + street_adress + " " + "chemi sakhvareli sachmelia" + " " + food + " " + " chemi sakhvareli sasmelia" + " " + drink + " " + "shemi sakhvareli sportia" + " " + sport + " " + "chemi facebook username aris" + " " + facebook + " " + "chemi instagram username aris" + " " + instagram + " " + "chemi wifi parolia" + " " + wifi)